vim9script

# Name:         gruber
# Description:  port of gruber colorscheme by John Gruber
# Author:       Charan Mandati <charancuz008@gmail.com>
# Last Change:  2026 Sep 26

# Generated by Colortemplate v3.0.0-rc2

set background=dark

hi clear
g:colors_name = 'gruber'

hi! link Boolean Normal
hi! link Character String
hi! link CursorColumn CursorLine
hi! link Folded FoldColumn
hi! link IncSearch CurSearch
hi! link Number Normal
hi! link Operator Normal
hi! link SignColumn FoldColumn
hi! link Special Normal
hi! link SpecialComment Comment
hi! link StorageClass Statement
hi! link Structure Statement
hi! link Title Normal
hi! link Typedef Statement

hi Normal guifg=#e4e4ef guibg=#181818 guisp=NONE gui=NONE ctermfg=254 ctermbg=234 cterm=NONE
hi Comment guifg=#cc8c3c guibg=bg guisp=NONE gui=NONE ctermfg=172 ctermbg=bg cterm=NONE
hi Constant guifg=#95a99f guibg=bg guisp=NONE gui=NONE ctermfg=109 ctermbg=bg cterm=NONE
hi CurSearch guifg=#000000 guibg=#f5f5f5 guisp=NONE gui=bold ctermfg=16 ctermbg=255 cterm=bold
hi Cursor guifg=fg guibg=bg guisp=NONE gui=reverse ctermfg=fg ctermbg=bg cterm=reverse
hi CursorLine guifg=fg guibg=#282828 guisp=NONE gui=NONE ctermfg=fg ctermbg=235 cterm=NONE
hi CursorLineNr guifg=#ffdd33 guibg=bg guisp=NONE gui=NONE ctermfg=220 ctermbg=bg cterm=NONE
hi DiffAdd guifg=#73c936 guibg=bg guisp=NONE gui=NONE ctermfg=76 ctermbg=bg cterm=NONE
hi DiffChange guifg=#96a6c8 guibg=bg guisp=NONE gui=NONE ctermfg=110 ctermbg=bg cterm=NONE
hi DiffDelete guifg=#f43841 guibg=bg guisp=NONE gui=NONE ctermfg=203 ctermbg=bg cterm=NONE
hi EndOfBuffer guifg=#282828 guibg=bg guisp=NONE gui=NONE ctermfg=235 ctermbg=bg cterm=NONE
hi FoldColumn guifg=#453d41 guibg=bg guisp=NONE gui=NONE ctermfg=238 ctermbg=bg cterm=NONE
hi Function guifg=#96a6c8 guibg=bg guisp=NONE gui=NONE ctermfg=110 ctermbg=bg cterm=NONE
hi Identifier guifg=#f4f4ff guibg=bg guisp=NONE gui=NONE ctermfg=255 ctermbg=bg cterm=NONE
hi LineNr guifg=#52494e guibg=bg guisp=NONE gui=NONE ctermfg=239 ctermbg=bg cterm=NONE
hi NonText guifg=#453d41 guibg=bg guisp=NONE gui=NONE ctermfg=238 ctermbg=bg cterm=NONE
hi Pmenu guifg=fg guibg=#282828 guisp=NONE gui=NONE ctermfg=fg ctermbg=235 cterm=NONE
hi PmenuMatch guifg=#73c936 guibg=bg guisp=NONE gui=NONE ctermfg=76 ctermbg=bg cterm=NONE
hi PmenuSbar guifg=#101010 guibg=#453d41 guisp=NONE gui=NONE ctermfg=233 ctermbg=238 cterm=NONE
hi PmenuSel guifg=fg guibg=#101010 guisp=NONE gui=NONE ctermfg=fg ctermbg=233 cterm=NONE
hi PmenuThumb guifg=bg guibg=bg guisp=NONE gui=NONE ctermfg=bg ctermbg=bg cterm=NONE
hi PreProc guifg=#95a99f guibg=bg guisp=NONE gui=NONE ctermfg=109 ctermbg=bg cterm=NONE
hi Search guifg=#f4f4ff guibg=#52494e guisp=NONE gui=NONE ctermfg=255 ctermbg=239 cterm=NONE
hi SpecialKey guifg=#282828 guibg=bg guisp=NONE gui=NONE ctermfg=235 ctermbg=bg cterm=NONE
hi Statement guifg=#ffdd33 guibg=bg guisp=NONE gui=bold ctermfg=220 ctermbg=bg cterm=bold
hi StatusLine guifg=fg guibg=#282828 guisp=NONE gui=bold ctermfg=fg ctermbg=235 cterm=bold
hi StatusLineNC guifg=#95a99f guibg=#282828 guisp=NONE gui=NONE ctermfg=109 ctermbg=235 cterm=NONE
hi String guifg=#73c936 guibg=bg guisp=NONE gui=NONE ctermfg=76 ctermbg=bg cterm=NONE
hi Tabline guifg=fg guibg=#282828 guisp=NONE gui=NONE ctermfg=fg ctermbg=235 cterm=NONE
hi TablineFill guifg=fg guibg=bg guisp=NONE gui=NONE ctermfg=fg ctermbg=bg cterm=NONE
hi TablineSel guifg=fg guibg=#52494e guisp=NONE gui=bold ctermfg=fg ctermbg=239 cterm=bold
hi TitleBar guifg=fg guibg=#202020 guisp=NONE gui=NONE ctermfg=fg ctermbg=234 cterm=NONE
hi TitleBarNC guifg=#797979 guibg=#202020 guisp=NONE gui=NONE ctermfg=243 ctermbg=234 cterm=NONE
hi Todo guifg=bg guibg=#9e95c7 guisp=NONE gui=NONE ctermfg=bg ctermbg=103 cterm=NONE
hi Type guifg=#95a99f guibg=bg guisp=NONE gui=NONE ctermfg=109 ctermbg=bg cterm=NONE
hi UnderLined guifg=#96a6c8 guibg=bg guisp=NONE gui=underline ctermfg=110 ctermbg=bg cterm=underline
hi VertSplit guifg=#453d41 guibg=bg guisp=NONE gui=NONE ctermfg=238 ctermbg=bg cterm=NONE
hi Visual guifg=fg guibg=#484848 guisp=NONE gui=NONE ctermfg=fg ctermbg=238 cterm=NONE

# vim: et ts=8 sw=2 sts=2
