vim9script

# Name:         gruber
# Description:  port of gruber colorscheme by John Gruber
# Author:       Charan Mandati <charancuz008@gmail.com>
# Last Change:  2026 Sep 24

# Generated by Colortemplate v3.0.0-rc2

set background=dark

hi clear
g:colors_name = 'gruber'

const t_Co = has('gui_running') ? 16777216 : str2nr(&t_Co)
const tgc = has('termguicolors') && &termguicolors

hi! link Character String
hi! link CursorColumn CursorLine
hi! link Folded FoldColumn
hi! link IncSearch CurSearch
hi! link Number Normal
hi! link Operator Normal
hi! link SignColumn FoldColumn
hi! link Special Normal
hi! link SpecialComment Comment
hi! link StorageClass Statement
hi! link Structure Statement
hi! link Title Normal
hi! link Typedef Statement

hi Normal guifg=#e4e4ef guibg=#181818 guisp=NONE gui=NONE ctermfg=254 ctermbg=234 cterm=NONE term=NONE
hi Comment guifg=#cc8c3c guibg=bg guisp=NONE gui=NONE ctermfg=172 ctermbg=bg cterm=NONE term=NONE
hi Constant guifg=#95a99f guibg=bg guisp=NONE gui=NONE ctermfg=109 ctermbg=bg cterm=NONE term=NONE
hi CurSearch guifg=#000000 guibg=#f5f5f5 guisp=NONE gui=bold ctermfg=16 ctermbg=255 cterm=bold term=bold
hi Cursor guifg=fg guibg=bg guisp=NONE gui=reverse ctermfg=fg ctermbg=bg cterm=reverse term=reverse
hi CursorLine guifg=fg guibg=#282828 guisp=NONE gui=NONE ctermfg=fg ctermbg=235 cterm=NONE term=NONE
hi CursorLineNr guifg=#ffdd33 guibg=bg guisp=NONE gui=NONE ctermfg=220 ctermbg=bg cterm=NONE term=NONE
hi DiffAdd guifg=#73c936 guibg=bg guisp=NONE gui=NONE ctermfg=76 ctermbg=bg cterm=NONE term=NONE
hi DiffChange guifg=#96a6c8 guibg=bg guisp=NONE gui=NONE ctermfg=110 ctermbg=bg cterm=NONE term=NONE
hi DiffDelete guifg=#f43841 guibg=bg guisp=NONE gui=NONE ctermfg=203 ctermbg=bg cterm=NONE term=NONE
hi EndOfBuffer guifg=#282828 guibg=bg guisp=NONE gui=NONE ctermfg=235 ctermbg=bg cterm=NONE term=NONE
hi FoldColumn guifg=#453d41 guibg=bg guisp=NONE gui=NONE ctermfg=238 ctermbg=bg cterm=NONE term=NONE
hi Function guifg=#96a6c8 guibg=bg guisp=NONE gui=NONE ctermfg=110 ctermbg=bg cterm=NONE term=NONE
hi Identifier guifg=#f4f4ff guibg=bg guisp=NONE gui=NONE ctermfg=255 ctermbg=bg cterm=NONE term=NONE
hi LineNr guifg=#52494e guibg=bg guisp=NONE gui=NONE ctermfg=239 ctermbg=bg cterm=NONE term=NONE
hi NonText guifg=#453d41 guibg=bg guisp=NONE gui=NONE ctermfg=238 ctermbg=bg cterm=NONE term=NONE
hi Pmenu guifg=fg guibg=#282828 guisp=NONE gui=NONE ctermfg=fg ctermbg=235 cterm=NONE term=NONE
hi PmenuMatch guifg=#73c936 guibg=bg guisp=NONE gui=NONE ctermfg=76 ctermbg=bg cterm=NONE term=NONE
hi PmenuSbar guifg=#101010 guibg=#453d41 guisp=NONE gui=NONE ctermfg=233 ctermbg=238 cterm=NONE term=NONE
hi PmenuSel guifg=fg guibg=#101010 guisp=NONE gui=NONE ctermfg=fg ctermbg=233 cterm=NONE term=NONE
hi PmenuThumb guifg=bg guibg=bg guisp=NONE gui=NONE ctermfg=bg ctermbg=bg cterm=NONE term=NONE
hi PreProc guifg=#95a99f guibg=bg guisp=NONE gui=NONE ctermfg=109 ctermbg=bg cterm=NONE term=NONE
hi Search guifg=#f4f4ff guibg=#52494e guisp=NONE gui=NONE ctermfg=255 ctermbg=239 cterm=NONE term=NONE
hi SpecialKey guifg=#282828 guibg=bg guisp=NONE gui=NONE ctermfg=235 ctermbg=bg cterm=NONE term=NONE
hi Statement guifg=#ffdd33 guibg=bg guisp=NONE gui=bold ctermfg=220 ctermbg=bg cterm=bold term=bold
hi StatusLine guifg=fg guibg=#282828 guisp=NONE gui=bold ctermfg=fg ctermbg=235 cterm=bold term=bold
hi StatusLineNC guifg=#95a99f guibg=#282828 guisp=NONE gui=NONE ctermfg=109 ctermbg=235 cterm=NONE term=NONE
hi String guifg=#73c936 guibg=bg guisp=NONE gui=NONE ctermfg=76 ctermbg=bg cterm=NONE term=NONE
hi Tabline guifg=fg guibg=#282828 guisp=NONE gui=NONE ctermfg=fg ctermbg=235 cterm=NONE term=NONE
hi TablineFill guifg=fg guibg=bg guisp=NONE gui=NONE ctermfg=fg ctermbg=bg cterm=NONE term=NONE
hi TablineSel guifg=fg guibg=#52494e guisp=NONE gui=bold ctermfg=fg ctermbg=239 cterm=bold term=bold
hi TitleBar guifg=fg guibg=#202020 guisp=NONE gui=NONE ctermfg=fg ctermbg=234 cterm=NONE term=NONE
hi TitleBarNC guifg=#797979 guibg=#202020 guisp=NONE gui=NONE ctermfg=243 ctermbg=234 cterm=NONE term=NONE
hi Todo guifg=bg guibg=#9e95c7 guisp=NONE gui=NONE ctermfg=bg ctermbg=103 cterm=NONE term=NONE
hi Type guifg=#95a99f guibg=bg guisp=NONE gui=NONE ctermfg=109 ctermbg=bg cterm=NONE term=NONE
hi UnderLined guifg=#96a6c8 guibg=bg guisp=NONE gui=underline ctermfg=110 ctermbg=bg cterm=underline term=underline
hi VertSplit guifg=#453d41 guibg=bg guisp=NONE gui=NONE ctermfg=238 ctermbg=bg cterm=NONE term=NONE
hi Visual guifg=fg guibg=#484848 guisp=NONE gui=NONE ctermfg=fg ctermbg=238 cterm=NONE term=NONE

if tgc || t_Co >= 256
  finish
endif

if t_Co >= 16
  hi Normal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Comment ctermfg=NONE ctermbg=bg cterm=NONE
  hi Constant ctermfg=NONE ctermbg=bg cterm=NONE
  hi CurSearch ctermfg=NONE ctermbg=NONE cterm=bold
  hi Cursor ctermfg=fg ctermbg=bg cterm=reverse
  hi CursorLine ctermfg=fg ctermbg=NONE cterm=NONE
  hi CursorLineNr ctermfg=NONE ctermbg=bg cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=bg cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=bg cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=bg cterm=NONE
  hi EndOfBuffer ctermfg=NONE ctermbg=bg cterm=NONE
  hi FoldColumn ctermfg=NONE ctermbg=bg cterm=NONE
  hi Function ctermfg=NONE ctermbg=bg cterm=NONE
  hi Identifier ctermfg=NONE ctermbg=bg cterm=NONE
  hi LineNr ctermfg=NONE ctermbg=bg cterm=NONE
  hi NonText ctermfg=NONE ctermbg=bg cterm=NONE
  hi Pmenu ctermfg=fg ctermbg=NONE cterm=NONE
  hi PmenuMatch ctermfg=NONE ctermbg=bg cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=NONE cterm=NONE
  hi PmenuSel ctermfg=fg ctermbg=NONE cterm=NONE
  hi PmenuThumb ctermfg=bg ctermbg=bg cterm=NONE
  hi PreProc ctermfg=NONE ctermbg=bg cterm=NONE
  hi Search ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=NONE ctermbg=bg cterm=NONE
  hi Statement ctermfg=NONE ctermbg=bg cterm=bold
  hi StatusLine ctermfg=fg ctermbg=NONE cterm=bold
  hi StatusLineNC ctermfg=NONE ctermbg=NONE cterm=NONE
  hi String ctermfg=NONE ctermbg=bg cterm=NONE
  hi Tabline ctermfg=fg ctermbg=NONE cterm=NONE
  hi TablineFill ctermfg=fg ctermbg=bg cterm=NONE
  hi TablineSel ctermfg=fg ctermbg=NONE cterm=bold
  hi TitleBar ctermfg=fg ctermbg=NONE cterm=NONE
  hi TitleBarNC ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Todo ctermfg=bg ctermbg=NONE cterm=NONE
  hi Type ctermfg=NONE ctermbg=bg cterm=NONE
  hi UnderLined ctermfg=NONE ctermbg=bg cterm=underline
  hi VertSplit ctermfg=NONE ctermbg=bg cterm=NONE
  hi Visual ctermfg=fg ctermbg=NONE cterm=NONE
  finish
endif

if t_Co >= 8
  hi Normal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Comment ctermfg=NONE ctermbg=bg cterm=NONE
  hi Constant ctermfg=NONE ctermbg=bg cterm=NONE
  hi CurSearch ctermfg=NONE ctermbg=NONE cterm=bold
  hi Cursor ctermfg=fg ctermbg=bg cterm=reverse
  hi CursorLine ctermfg=fg ctermbg=NONE cterm=NONE
  hi CursorLineNr ctermfg=NONE ctermbg=bg cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=bg cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=bg cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=bg cterm=NONE
  hi EndOfBuffer ctermfg=NONE ctermbg=bg cterm=NONE
  hi FoldColumn ctermfg=NONE ctermbg=bg cterm=NONE
  hi Function ctermfg=NONE ctermbg=bg cterm=NONE
  hi Identifier ctermfg=NONE ctermbg=bg cterm=NONE
  hi LineNr ctermfg=NONE ctermbg=bg cterm=NONE
  hi NonText ctermfg=NONE ctermbg=bg cterm=NONE
  hi Pmenu ctermfg=fg ctermbg=NONE cterm=NONE
  hi PmenuMatch ctermfg=NONE ctermbg=bg cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=NONE cterm=NONE
  hi PmenuSel ctermfg=fg ctermbg=NONE cterm=NONE
  hi PmenuThumb ctermfg=bg ctermbg=bg cterm=NONE
  hi PreProc ctermfg=NONE ctermbg=bg cterm=NONE
  hi Search ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=NONE ctermbg=bg cterm=NONE
  hi Statement ctermfg=NONE ctermbg=bg cterm=bold
  hi StatusLine ctermfg=fg ctermbg=NONE cterm=bold
  hi StatusLineNC ctermfg=NONE ctermbg=NONE cterm=NONE
  hi String ctermfg=NONE ctermbg=bg cterm=NONE
  hi Tabline ctermfg=fg ctermbg=NONE cterm=NONE
  hi TablineFill ctermfg=fg ctermbg=bg cterm=NONE
  hi TablineSel ctermfg=fg ctermbg=NONE cterm=bold
  hi TitleBar ctermfg=fg ctermbg=NONE cterm=NONE
  hi TitleBarNC ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Todo ctermfg=bg ctermbg=NONE cterm=NONE
  hi Type ctermfg=NONE ctermbg=bg cterm=NONE
  hi UnderLined ctermfg=NONE ctermbg=bg cterm=underline
  hi VertSplit ctermfg=NONE ctermbg=bg cterm=NONE
  hi Visual ctermfg=fg ctermbg=NONE cterm=NONE
  finish
endif

# vim: et ts=8 sw=2 sts=2
